document.addEventListener('DOMContentLoaded', () => {
    const questionContainer = document.getElementById('question')
    const answersContainer = document.getElementById('answers')
    const resultContainer = document.getElementById('result')
    const progressContainer = document.getElementById('progress')
    const currentScoreDisplay = document.getElementById('currentScore')
    const highScoreDisplay = document.getElementById('highScore')
    const gameSetupDiv = document.getElementById('game-setup')
    const quizDiv = document.getElementById('quiz')
    const categorySelect = document.getElementById('categoria')
    const quantidadeInput = document.getElementById('quantidade')
    const dificuldadeSelect = document.getElementById('dificuldade')
    const startButton = document.getElementById('start-btn')
})